workflows:
  expo-ios:
    name: Expo iOS Build
    max_build_duration: 60
    environment:
      node: 16.20.0
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          npx expo install
      - name: Expo export
        script: |
          npx expo export --platform ios --output-dir dist
    artifacts:
      - dist/**



