workflows:
  expo-ios:
    name: Expo iOS Build
    max_build_duration: 60
    environment:
      node: 16.20.0
      expo: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Expo build for iOS
        script: |
          npx expo install
          npx expo export --platform ios
    artifacts:
      - dist/**


